---
extends: default

rules:
  document-start:
    level: error
  truthy: disable
  comments:
    level: error
  line-length:
    max: 512
    level: warning

ignore: |
  # yamllint does not understand erb template
  .tox
  config/.esphome
  decoder/.pio
